export const COLOR_MODE = {
  LIGHT: { value: "light", color: "#d9d9d9cc" },
  DARK: { value: "dark", color: "black" },
  BLUE: { value: "blue", color: "blue" },
  GREEN: { value: "green", color: "green" },
  BROWN: { value: "brown", color: "brown" },
  PINK: { value: "pink", color: "pink" },
};

export const COLOR_MODE_CHILDREN = {
  LIGHT: {
    text: "#292828",
    background: "#ffffff",
    header: "#ff0000",
    footer: "#000000",
    quoteBgc: "#ffffff",
    quoteTitle: "#626060",
    quoteBody: "#626060",
    quoteBorder: "#dedede",
    border: "#dedede",
    text_footer: "white",
  },
  DARK: {
    text: "#ffffff",
    background: "#292828",
    header: "#333333",
    footer: "#ededed",
    quoteBgc: "#595959",
    quoteTitle: "#ffffff",
    quoteBody: "#ffffff",
    quoteBorder: "#969696",
    border: "#c7c7c7",
    text_footer: "white",
  },
  BLUE: {
    text: "#292828",
    background: "#f0fbff",
    header: "#add8e6",
    footer: "#225a6d",
    quoteBgc: "#ffffff",
    quoteTitle: "#225a6d",
    quoteBody: "#616161",
    quoteBorder: "#dedede",
    border: "#dedede",
    text_footer: "white",
  },
  GREEN: {
    text: "#a3f5cc",
    background: "#0a5c33",
    header: "#084526",
    footer: "#a3f5cc",
    quoteBgc: "#5cd699",
    quoteTitle: "#03300a",
    quoteBody: "#082b0e",
    quoteBorder: "#0a5c18",
    border: "#33ffdd",
    text_footer: "white",
  },
  BROWN: {
    text: "#333333",
    background: "#eba028",
    header: "#d99a26",
    footer: "#4d3b19",
    quoteBgc: "#ffe666",
    quoteTitle: "#4b402f",
    quoteBody: "#4b3d2f",
    quoteBorder: "#bfaa40",
    border: "#dfbc20",
    text_footer: "white",
  },
  PINK: {
    text: "#8f008f",
    background: "#f9c8f9",
    header: "#ffc2cc",
    footer: "#4f404f",
    quoteBgc: "#e3abb4",
    quoteTitle: "#6b246b",
    quoteBody: "#56394c",
    quoteBorder: "#6b246b",
    border: "#c95ec9",
    text_footer: "white",
  },
};
